{{- if and .Values.dataPersistency.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "bitcoin-core.persistenVolumeName" . }}
spec:
  storageClassName: {{ .Values.dataPersistency.storageClass }}
  accessModes:
    {{- range $.Values.dataPersistency.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.dataPersistency.capacity }}
{{- end }}
