{{- if and .Values.dataPersistency.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.dataPersistency.storageClass }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
{{- end }}